#!/usr/bin/env python3
"""Phase 2 env codemod — rename MARS_* env vars to MARS_* with word boundaries.

Usage:
    python3 scripts/env-codemod.py --dry-run     # write ENV_CODEMOD_DRYRUN.md
    python3 scripts/env-codemod.py --apply       # rewrite files in place

Rules (final decisions):
- \\bOMP_[A-Z0-9_]*\\b -> MARS_<same suffix>. Word boundary matching only, so
  ROBOMP_* (e.g. ROBOMP_MODEL) and PI_* are never touched.
- No MARS_* fallback aliases are added.
- PI_PROFILE is kept as-is; MARS_PROFILE becomes MARS_PROFILE (the alias logic
  in packages/utils/src/dirs.ts keeps PI_PROFILE as legacy fallback).
- These files are excluded and handled by hand / later phases:
  ENV_RENAME_MAP.md, REBRAND_AUDIT.md, REBRAND_CODEMOD_DRYRUN.md (history),
  HANDOFF.md (updated by hand), ENV_CODEMOD_DRYRUN.md (this script's report),
  CHANGELOG.md files (released history is immutable), bun.lock (regenerated by
  `bun install`), .zst binary assets.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import os
import re
import sys

PATTERN = re.compile(r"\bOMP_[A-Z0-9_]*\b")

EXCLUDED_EXACT = {
    "ENV_RENAME_MAP.md",
    "ENV_CODEMOD_DRYRUN.md",
    "REBRAND_AUDIT.md",
    "REBRAND_CODEMOD_DRYRUN.md",
    "HANDOFF.md",
    "bun.lock",
}

EXCLUDED_BASENAMES = {"CHANGELOG.md"}

EXCLUDED_SUFFIXES = (".zst",)

SKIP_DIRS = {".git", "node_modules", "dist", "target", "binaries", "bazel-out", "__pycache__"}


def _prune_dirs(rel_dir: str, dirnames: list[str]) -> None:
    """Drop generated/foreign trees. `bazel-*` are Bazel's convenience symlinks
    at the repo root only — never real source dirs like
    `.github/actions/bazel-cache/`."""
    keep = []
    for name in dirnames:
        if name in SKIP_DIRS:
            continue
        if rel_dir == "." and name.startswith("bazel-"):
            continue
        keep.append(name)
    dirnames[:] = sorted(keep)


def list_files(root: str) -> list[str]:
    out: list[str] = []
    for dirpath, dirnames, filenames in os.walk(root):
        rel_dir = os.path.relpath(dirpath, root)
        _prune_dirs(rel_dir, dirnames)
        for name in sorted(filenames):
            rel = name if rel_dir == "." else os.path.join(rel_dir, name)
            out.append(rel)
    return sorted(out)



def is_excluded(rel: str) -> bool:
    if rel in EXCLUDED_EXACT:
        return True
    if os.path.basename(rel) in EXCLUDED_BASENAMES:
        return True
    if rel.endswith(EXCLUDED_SUFFIXES):
        return True
    return False


def replace_match(match: re.Match[str]) -> str:
    return "MARS_" + match.group(0)[len("MARS_") :]


def main() -> int:
    parser = argparse.ArgumentParser(description="MARS_* -> MARS_* env codemod")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()
    if args.dry_run == args.apply:
        print("specify exactly one of --dry-run or --apply", file=sys.stderr)
        return 2

    root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    files = list_files(root)

    touched: dict[str, str] = {}
    skipped: list[str] = []
    per_file: dict[str, dict[str, int]] = {}
    errors: list[str] = []
    total_edits = 0

    for rel in files:
        if is_excluded(rel):
            skipped.append(rel)
            continue
        abs_path = os.path.join(root, rel)
        try:
            with open(abs_path, "r", encoding="utf-8") as fh:
                text = fh.read()
        except (OSError, UnicodeDecodeError) as error:
            # Binary or unreadable files are skipped, not rewritten.
            continue
        new_text, count = PATTERN.subn(replace_match, text)
        if count:
            touched[rel] = new_text
            total_edits += count
            pairs: dict[str, int] = {}
            for match in PATTERN.finditer(text):
                before = match.group(0)
                after = "MARS_" + before[len("MARS_") :]
                pair = f"{before} -> {after}"
                pairs[pair] = pairs.get(pair, 0) + 1
            per_file[rel] = pairs

    lines: list[str] = []
    lines.append("# ENV_CODEMOD — dry run" if args.dry_run else "# ENV_CODEMOD — applied")
    lines.append("")
    lines.append(f"Generated: {_dt.datetime.now(_dt.timezone.utc).isoformat(timespec='seconds')}")
    lines.append(f"Mode: {'dry-run' if args.dry_run else 'apply'}")
    lines.append(f"Rule: \\bOMP_[A-Z0-9_]*\\b -> MARS_<suffix>")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- files scanned: {len(files)}")
    lines.append(f"- files touched: {len(touched)}")
    lines.append(f"- total edits: {total_edits}")
    lines.append(f"- excluded files skipped: {len(skipped)}")
    lines.append("")
    lines.append("### Excluded (kept MARS_* on purpose)")
    lines.append("")
    for rel in sorted(skipped):
        lines.append(f"- `{rel}`")
    lines.append("")
    lines.append("### Per-file detail")
    lines.append("")
    groups: dict[str, list[str]] = {}
    for rel in touched:
        key = "/".join(rel.split("/")[:2])
        groups.setdefault(key, []).append(rel)
    for group in sorted(groups):
        lines.append(f"#### {group}")
        lines.append("")
        for rel in sorted(groups[group]):
            lines.append(f"- `{rel}`")
            for pair, n in sorted(per_file[rel].items()):
                suffix = f" x{n}" if n > 1 else ""
                lines.append(f"  - `{pair}`{suffix}")
        lines.append("")
    if errors:
        lines.append("### Errors")
        lines.append("")
        for err in errors[:50]:
            lines.append(f"- {err}")
        lines.append("")

    report_path = os.path.join(root, "ENV_CODEMOD_DRYRUN.md")
    with open(report_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {report_path}")
    print(f"files touched: {len(touched)}, edits: {total_edits}")

    if args.apply:
        for rel, text in touched.items():
            with open(os.path.join(root, rel), "w", encoding="utf-8") as fh:
                fh.write(text)
        print(f"applied {len(touched)} file(s)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
